steps:
  - name: 'bash'
    args:
      - '-c'
      - |
        echo "=== Verifying build context ==="
        echo "Current directory: $(pwd)"
        echo ""
        echo "Checking for required files:"
        if [ ! -f "pnpm-workspace.yaml" ]; then
          echo "ERROR: pnpm-workspace.yaml not found!"
          echo "Listing all .yaml files:"
          find . -name "*.yaml" -type f | head -10
          exit 1
        fi
        if [ ! -f "package.json" ]; then
          echo "ERROR: package.json not found!"
          exit 1
        fi
        if [ ! -f "pnpm-lock.yaml" ]; then
          echo "ERROR: pnpm-lock.yaml not found!"
          exit 1
        fi
        echo "✓ pnpm-workspace.yaml found"
        echo "✓ package.json found"
        echo "✓ pnpm-lock.yaml found"
        echo ""
        echo "File contents check:"
        cat pnpm-workspace.yaml
        echo ""
        echo "=== Build context verified ==="
    id: 'verify-files'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/backend/Dockerfile'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/vibe/vibe-api:${SHORT_SHA}'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/vibe/vibe-api:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    dir: '.'
    id: 'build'
    env:
      - 'DOCKER_BUILDKIT=1'
    waitFor: ['verify-files']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/vibe/vibe-api'
    id: 'push'

images:
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/vibe/vibe-api:${SHORT_SHA}'
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/vibe/vibe-api:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
