version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - apps/backend/.env
    environment:
      # Override specific variables for Docker
      PORT: 3001
      GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/callback
      FRONTEND_URL: http://localhost:5173

    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/apps/backend/logs

    restart: unless-stopped

    networks:
      - vibe-network

networks:
  vibe-network:
    driver: bridge
